// CHRISTOPHER D'ENTREMONT 
// 20160623 - SDV701 - ASSESSMENT 1 PHASE 2 - PROPERTY (LOCATION / LEASE) APPLICATION
// TIERED SOFTWARE C# APPLICATION
// PROPERTY2SELFHOST / PROPERTY_DATAENTITIES CLASS
// AUTOGENERATED CODE FOR DATA ENTITIES - SUPPORTS DB VISUAL MODEL.edmx
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property2Selfhost
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class Property_DataEntities : DbContext
    {
        public Property_DataEntities()
            : base("name=Property_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Property> Properties { get; set; }
    }
}
