//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property2Selfhost
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Applications = new HashSet<Application>();
        }
    
        public int Property_ID { get; set; }
        public System.DateTime Date_Modified { get; set; }
        public decimal Lease_Rate { get; set; }
        public string Owner { get; set; }
        public byte[] TimestStamp { get; set; }
        public string Address { get; set; }
        public int Location_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        public virtual Location Location { get; set; }
    }
}
