//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Property2Selfhost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residential : Property
    {
        public Nullable<int> Residential_Bond { get; set; }
    }
}
