//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Property_DataModel", "FK_PROPERTY_LOCATION", "Location", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(PropertySelfhost.Location), "Property", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(PropertySelfhost.Property), true)]

#endregion

namespace PropertySelfhost
{
    #region Contexts

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Property_DataEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Property_DataEntities object using the connection string found in the 'Property_DataEntities' section of the application configuration file.
        /// </summary>
        public Property_DataEntities() : base("name=Property_DataEntities", "Property_DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Property_DataEntities object.
        /// </summary>
        public Property_DataEntities(string connectionString) : base(connectionString, "Property_DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Property_DataEntities object.
        /// </summary>
        public Property_DataEntities(EntityConnection connection) : base(connection, "Property_DataEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Location> Locations
        {
            get
            {
                if ((_Locations == null))
                {
                    _Locations = base.CreateObjectSet<Location>("Locations");
                }
                return _Locations;
            }
        }
        private ObjectSet<Location> _Locations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Property> Properties
        {
            get
            {
                if ((_Properties == null))
                {
                    _Properties = base.CreateObjectSet<Property>("Properties");
                }
                return _Properties;
            }
        }
        private ObjectSet<Property> _Properties;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Locations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLocations(Location location)
        {
            base.AddObject("Locations", location);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Properties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProperties(Property property)
        {
            base.AddObject("Properties", property);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Property_DataModel", Name="Location")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Location : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Location object.
        /// </summary>
        /// <param name="location_ID">Initial value of the Location_ID property.</param>
        public static Location CreateLocation(global::System.String location_ID)
        {
            Location location = new Location();
            location.Location_ID = location_ID;
            return location;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location_ID
        {
            get
            {
                return _Location_ID;
            }
            set
            {
                if (_Location_ID != value)
                {
                    OnLocation_IDChanging(value);
                    ReportPropertyChanging("Location_ID");
                    _Location_ID = StructuralObject.SetValidValue(value, false, "Location_ID");
                    ReportPropertyChanged("Location_ID");
                    OnLocation_IDChanged();
                }
            }
        }
        private global::System.String _Location_ID;
        partial void OnLocation_IDChanging(global::System.String value);
        partial void OnLocation_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City_Name
        {
            get
            {
                return _City_Name;
            }
            set
            {
                OnCity_NameChanging(value);
                ReportPropertyChanging("City_Name");
                _City_Name = StructuralObject.SetValidValue(value, true, "City_Name");
                ReportPropertyChanged("City_Name");
                OnCity_NameChanged();
            }
        }
        private global::System.String _City_Name;
        partial void OnCity_NameChanging(global::System.String value);
        partial void OnCity_NameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location_Detail
        {
            get
            {
                return _Location_Detail;
            }
            set
            {
                OnLocation_DetailChanging(value);
                ReportPropertyChanging("Location_Detail");
                _Location_Detail = StructuralObject.SetValidValue(value, true, "Location_Detail");
                ReportPropertyChanged("Location_Detail");
                OnLocation_DetailChanged();
            }
        }
        private global::System.String _Location_Detail;
        partial void OnLocation_DetailChanging(global::System.String value);
        partial void OnLocation_DetailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Property_DataModel", "FK_PROPERTY_LOCATION", "Property")]
        public EntityCollection<Property> Property_ID
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Property>("Property_DataModel.FK_PROPERTY_LOCATION", "Property");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Property>("Property_DataModel.FK_PROPERTY_LOCATION", "Property", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Property_DataModel", Name="Property")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Property : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Property object.
        /// </summary>
        /// <param name="property_Type">Initial value of the Property_Type property.</param>
        /// <param name="property_ID">Initial value of the Property_ID property.</param>
        /// <param name="date_Modified">Initial value of the Date_Modified property.</param>
        /// <param name="lease_Rate">Initial value of the Lease_Rate property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static Property CreateProperty(global::System.String property_Type, global::System.String property_ID, global::System.DateTime date_Modified, global::System.Decimal lease_Rate, global::System.String address)
        {
            Property property = new Property();
            property.Property_Type = property_Type;
            property.Property_ID = property_ID;
            property.Date_Modified = date_Modified;
            property.Lease_Rate = lease_Rate;
            property.Address = address;
            return property;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Property_Type
        {
            get
            {
                return _Property_Type;
            }
            set
            {
                OnProperty_TypeChanging(value);
                ReportPropertyChanging("Property_Type");
                _Property_Type = StructuralObject.SetValidValue(value, false, "Property_Type");
                ReportPropertyChanged("Property_Type");
                OnProperty_TypeChanged();
            }
        }
        private global::System.String _Property_Type;
        partial void OnProperty_TypeChanging(global::System.String value);
        partial void OnProperty_TypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Property_ID
        {
            get
            {
                return _Property_ID;
            }
            set
            {
                if (_Property_ID != value)
                {
                    OnProperty_IDChanging(value);
                    ReportPropertyChanging("Property_ID");
                    _Property_ID = StructuralObject.SetValidValue(value, false, "Property_ID");
                    ReportPropertyChanged("Property_ID");
                    OnProperty_IDChanged();
                }
            }
        }
        private global::System.String _Property_ID;
        partial void OnProperty_IDChanging(global::System.String value);
        partial void OnProperty_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date_Modified
        {
            get
            {
                return _Date_Modified;
            }
            set
            {
                OnDate_ModifiedChanging(value);
                ReportPropertyChanging("Date_Modified");
                _Date_Modified = StructuralObject.SetValidValue(value, "Date_Modified");
                ReportPropertyChanged("Date_Modified");
                OnDate_ModifiedChanged();
            }
        }
        private global::System.DateTime _Date_Modified;
        partial void OnDate_ModifiedChanging(global::System.DateTime value);
        partial void OnDate_ModifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Lease_Rate
        {
            get
            {
                return _Lease_Rate;
            }
            set
            {
                OnLease_RateChanging(value);
                ReportPropertyChanging("Lease_Rate");
                _Lease_Rate = StructuralObject.SetValidValue(value, "Lease_Rate");
                ReportPropertyChanged("Lease_Rate");
                OnLease_RateChanged();
            }
        }
        private global::System.Decimal _Lease_Rate;
        partial void OnLease_RateChanging(global::System.Decimal value);
        partial void OnLease_RateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Owner
        {
            get
            {
                return _Owner;
            }
            set
            {
                OnOwnerChanging(value);
                ReportPropertyChanging("Owner");
                _Owner = StructuralObject.SetValidValue(value, true, "Owner");
                ReportPropertyChanged("Owner");
                OnOwnerChanged();
            }
        }
        private global::System.String _Owner;
        partial void OnOwnerChanging(global::System.String value);
        partial void OnOwnerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> Row_Version
        {
            get
            {
                return _Row_Version;
            }
            set
            {
                OnRow_VersionChanging(value);
                ReportPropertyChanging("Row_Version");
                _Row_Version = StructuralObject.SetValidValue(value, "Row_Version");
                ReportPropertyChanged("Row_Version");
                OnRow_VersionChanged();
            }
        }
        private Nullable<global::System.Single> _Row_Version;
        partial void OnRow_VersionChanging(Nullable<global::System.Single> value);
        partial void OnRow_VersionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Fabric
        {
            get
            {
                return _Fabric;
            }
            set
            {
                OnFabricChanging(value);
                ReportPropertyChanging("Fabric");
                _Fabric = StructuralObject.SetValidValue(value, true, "Fabric");
                ReportPropertyChanged("Fabric");
                OnFabricChanged();
            }
        }
        private global::System.String _Fabric;
        partial void OnFabricChanging(global::System.String value);
        partial void OnFabricChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                if (_Address != value)
                {
                    OnAddressChanging(value);
                    ReportPropertyChanging("Address");
                    _Address = StructuralObject.SetValidValue(value, false, "Address");
                    ReportPropertyChanged("Address");
                    OnAddressChanged();
                }
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Property_DataModel", "FK_PROPERTY_LOCATION", "Location")]
        public Location Location_ID
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Location>("Property_DataModel.FK_PROPERTY_LOCATION", "Location").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Location>("Property_DataModel.FK_PROPERTY_LOCATION", "Location").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Location> Location_IDReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Location>("Property_DataModel.FK_PROPERTY_LOCATION", "Location");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Location>("Property_DataModel.FK_PROPERTY_LOCATION", "Location", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
