//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertySelfhost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public string Property_Type { get; set; }
        public string Property_ID { get; set; }
        public System.DateTime Date_Modified { get; set; }
        public decimal Lease_Rate { get; set; }
        public string Owner { get; set; }
        public Nullable<float> Row_Version { get; set; }
        public string Fabric { get; set; }
        public string Address { get; set; }
    
        public virtual Location Location_ID { get; set; }
    }
}
