//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery3Selfhost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sculpture : Work
    {
        public Nullable<float> Weight { get; set; }
        public string Material { get; set; }
    }
}
