//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gallery3Selfhost
{
    using System;
    using System.Collections.Generic;
    
    public abstract partial class Work
    {
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Value { get; set; }
        public string ArtistName { get; set; }
    }
}
